language: python

sudo: required  # needed for dist: trusty
dist: trusty  # needed for libenchant1c2a

python:
  - "3.3"

addons:
  postgresql: '9.4'

before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install libenchant1c2a  # needed for pyenchant
  - pip install -U pip
  - python setup.py develop
  - pip freeze # dump the versions of all pip packages for reproducibility


script: "py.test -v"
